### ISSUE TITLE
1.8.8: build is failing

### ISSUE THREAD

**Issue by kloczek** [mike-fabian/ibus-table-chinese#5]
List of installed modules in build env:
```console
Package         Version
--------------- --------------
cycler          0.11.0
distro          1.6.0
extras          1.0.0
fixtures        3.0.0
fonttools       4.29.0
gpg             1.17.0-unknown
kiwisolver      1.3.2
libcomps        0.1.18
matplotlib      3.5.1
meson           0.61.2
numpy           1.22.3
olefile         0.46
packaging       21.3
pbr             5.8.0
Pillow          9.0.0
pip             22.0.3
PyGObject       3.42.0
pyparsing       3.0.7
python-dateutil 2.8.2
rpm             4.17.0
six             1.16.0
testtools       2.5.0
```
In build env is installed ibus-table 1.16.7.
Build is failing with:
```console
[tkloczko@devel-g2v noarch-redhat-linux-gnu]$ make
/usr/bin/cmake -S/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8 -B/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu/CMakeFiles /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu'
make  -f tables/yong/CMakeFiles/convert_yong.dir/build.make tables/yong/CMakeFiles/convert_yong.dir/depend
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu'
cd /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8 /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/tables/yong /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu/tables/yong /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu/tables/yong/CMakeFiles/convert_yong.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu'
make  -f tables/yong/CMakeFiles/convert_yong.dir/build.make tables/yong/CMakeFiles/convert_yong.dir/build
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu'
[  2%] Building yong table
cd /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu/tables/yong && /usr/bin/ibus-table-createdb -n yong.db -s /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/tables/yong/yong.txt
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/tabcreatedb.py", line 164, in <module>
    class Section:
  File "/usr/share/ibus-table/engine/tabcreatedb.py", line 168, in Section
    patt: re.Pattern[str]
TypeError: 'type' object is not subscriptable
make[2]: *** [tables/yong/CMakeFiles/convert_yong.dir/build.make:77: tables/yong/yong.db] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:937: tables/yong/CMakeFiles/convert_yong.dir/all] Error 2
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.8/noarch-redhat-linux-gnu'
make: *** [Makefile:127: all] Error 2
```

**Comment by mike-fabian** [comment]
Is this reproducible with ibus-table-1.16.8?

I cannot reproduce it with ibus-table-1.16.8 and there seem to be no relevant changes between ibus-table-1.6.7 and ibus-table-1.6.8 which could have an effect on this.

**Comment by mike-fabian** [comment]
```
  File "/usr/share/ibus-table/engine/tabcreatedb.py", line 168, in Section
    patt: re.Pattern[str]
TypeError: 'type' object is not subscriptable
```

This seems to fail parsing  a type hint.

Maybe your Python version is too old?

I am currently using:

```
$ python3 --version 
Python 3.10.4
```

**Comment by kloczek** [comment]
I'm using python 3.8.13 and above was with ibus-table 1.16.8.

**Comment by mike-fabian** [comment]
Maybe Python 3.8 has a bug in parsing this type hint above?

**Comment by kloczek** [comment]
Probability of that would be very low because +950 other modules which have many python 3.1{0,1} adaptations works without similar effects.

**Comment by mike-fabian** [comment]
But I cannot see that the type hint 

```
patt: re.Pattern[str]
```

is wrong. Is there anything wrong with that type hint I am missing?

**Comment by mike-fabian** [comment]
```
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables/yong (release-candidate-1.8.9 %)
$ python3.10 /local/mfabian/src/ibus-table/engine/tabcreatedb.py -s yong.txt -n yong 
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables/yong (release-candidate-1.8.9 %)
$ python3.8 /local/mfabian/src/ibus-table/engine/tabcreatedb.py -s yong.txt -n yong 
Traceback (most recent call last):
  File "/local/mfabian/src/ibus-table/engine/tabcreatedb.py", line 164, in <module>
    class Section:
  File "/local/mfabian/src/ibus-table/engine/tabcreatedb.py", line 168, in Section
    patt: re.Pattern[str]
TypeError: 'type' object is not subscriptable
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables/yong (release-candidate-1.8.9 %)
$ 
```

**Comment by mike-fabian** [comment]
Looks like a problem in python3.8 to me.

**Comment by kloczek** [comment]
If python 3.8 is no longer supported it shopuld be some error mesage during configure execution.

**Comment by mike-fabian** [comment]
> If python 3.8 is no longer supported it shopuld be some error mesage during configure execution.

Well, I didn’t know until now that Python 3.8 has this bug. Thinking about what I should do ...

**Comment by mike-fabian** [comment]
Python 3.9 works.

**Comment by mike-fabian** [comment]
So now I wonder whether I should require Python 3.9 or tweak the type hint a bit to make Python 3.8 work as well ...

**Comment by kloczek** [comment]
All pythons provides python pkgconfig file so that kind of check would be easy to add.
Nevertheless 2.8 still is officially supported so ..

**Comment by mike-fabian** [comment]
> Nevertheless 2.8 still is officially supported so ..

Is that a typo? I guess you mean 3.8 ...

I think I’ll make it work with 3.8 and add a requirement for 3.8.

**Comment by mike-fabian** [comment]
Should work with Python >= 3.6:

https://github.com/mike-fabian/ibus-table/releases/tag/1.16.9

**Comment by kloczek** [comment]
> > Nevertheless 2.8 still is officially supported so ..
> 
> Is that a typo? I guess you mean 3.8 ...
> 
> I think I’ll make it work with 3.8 and add a requirement for 3.8.

Yes it is typo.

**Comment by kloczek** [comment]
Just tested ibus-table-chinese build in buld env with ibus-table + https://github.com/mike-fabian/ibus-table/commit/7c3573745407414ba7d6cb8c9a9b0b42bceaf2bd and I was able sucessfully finish build.
Thank you very much 👍
